package rpcprotocol;

import java.io.Serializable;

public enum RequestType implements Serializable {
    LOGIN_MEDIC, LOGIN_FARMACIST, LOGOUT_MEDIC, LOGOUT_FARMACIST,
    ADD_COMANDA, ADD_MEDICAMENT, FIND_ALL_COMENZI, FIND_ALL_MEDICAMENTE,
    FIND_ALL_MEDICI,FIND_ALL_ELEM_CMD, FIND_MEDICAMENT_BY_DENUMIRE, STERGE_COMANDA,
    STERGE_MEDICAMENT, UPDATE_MEDS, UPDATE_ELEM_CMD, UPDATE_COMANDA;
}
